version: 2

submodules:
  include: all
  recursive: true

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements_rtd.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
      - pip install pip-tools
      - pip-compile pyproject.toml --quiet --no-annotate --no-header --strip-extras --extra dev --extra docs -o requirements_rtd.txt
