name: Build image

inputs:
  docker_file:
    description: "The docker file."
    required: True
  platforms:
    description: "Platforms to build for (csv)."
    default: "linux/amd64,linux/arm64"
  tags:
    description: "Image tags (csv)."
    required: True
  build_only:
    description: "'true' or 'false'."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU 🌈
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx ✨
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub 🎪
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and deploy image 🐳
      uses: docker/build-push-action@v5
      with:
        context: docker
        file: ${{ inputs.docker_file }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.build_only != 'true' }}
        tags: ${{ inputs.tags }}
