FROM almalinux:9

ARG TARGETPLATFORM

# labels
LABEL law_version="0.1.20"
LABEL law.image-name="riga/law"
LABEL law.image-tag="a9-py39"
LABEL law.image-os="almalinux9"
LABEL law.image-python-major="3"
LABEL law.image-python-minor="9"
LABEL law.image-python="3.9"

# law specific environment variables
ENV LAW_IMAGE_ROOT /root/law
ENV LAW_IMAGE_NAME riga/law
ENV LAW_IMAGE_TAG a9-py39
ENV LAW_IMAGE_PYTHON_MAJOR 3
ENV LAW_IMAGE_PYTHON_MINOR 9
ENV LAW_IMAGE_PYTHON ${LAW_IMAGE_PYTHON_MAJOR}.${LAW_IMAGE_PYTHON_MINOR}
ENV LAW_MAMBA_ROOT /root/mamba
ENV LAW_SANDBOX docker::riga/law:a9-py39,docker::riga/law:py39

# exposed ports
EXPOSE 8082

# bash files
COPY bash_profile /root/.bash_profile
COPY bashrc /root/.bashrc

# installation workdir
WORKDIR /root/install

# prepare yum
RUN yum -y update; yum clean all
RUN yum -y install --allowerasing yum-utils epel-release curl wget bzip2; yum clean all

# setup mamba
ENV MAMBA_ROOT_PREFIX "${LAW_MAMBA_ROOT}"
ENV MAMBA_EXE "${MAMBA_ROOT_PREFIX}/bin/micromamba"
ENV PATH "${MAMBA_ROOT_PREFIX}/bin:${PATH}"
RUN case "${TARGETPLATFORM}" in \
        "linux/amd64") MAMBA_PLATFORM="linux-64" ;; \
        "linux/arm64") MAMBA_PLATFORM="linux-aarch64" ;; \
        "darwin/amd64") MAMBA_PLATFORM="osx-64" ;; \
        "darwin/arm64") MAMBA_PLATFORM="osx-arm64" ;; \
        *) MAMBA_PLATFORM="linux-64" ;; \
    esac && \
    mkdir -p "${MAMBA_ROOT_PREFIX}" && \
    curl -Ls "https://micro.mamba.pm/api/micromamba/${MAMBA_PLATFORM}/latest" | tar -xvj -C "${MAMBA_ROOT_PREFIX}" "bin/micromamba"
RUN echo $'\n\
changeps1: false\n\
always_yes: true\n\
channels:\n\
  - conda-forge\n\
' >> "${MAMBA_ROOT_PREFIX}/.condarc"
SHELL ["micromamba", "run", "-n", "base", "/bin/bash", "-c"]

# mamba packages
RUN micromamba install "python=${LAW_IMAGE_PYTHON_MAJOR}.${LAW_IMAGE_PYTHON_MINOR}" gcc which wget nano micro git git-lfs cmake ncurses readline && \
    micromamba clean --all
RUN micromamba install gfal2 gfal2-util python-gfal2 && \
    micromamba clean --all

# python packages
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade setuptools

# cleanup installation workdir
WORKDIR /root
RUN rm -rf /root/install

# install law master
RUN git clone --recursive https://github.com/riga/law "${LAW_IMAGE_ROOT}" && \
    cd "${LAW_IMAGE_ROOT}" && \
    pip install --no-cache-dir -r requirements.txt -r requirements_dev.txt && \
    pip install --no-cache-dir mypy && \
    pip install --no-cache-dir .
WORKDIR ${LAW_IMAGE_ROOT}

# default shell
SHELL ["micromamba", "run", "-n", "base", "/bin/bash", "-i", "--login"]
