FROM riga/law:latest

# labels
LABEL law.image_name="riga/law"
LABEL law.image_tag="example"

# copy files
COPY start_example.sh /root/start_example.sh

# workdir
WORKDIR /root

# update the law repository
RUN cd "${LAW_IMAGE_SOURCE_DIR}" && git pull

# entry point
ENTRYPOINT ["/root/start_example.sh"]
CMD ["loremipsum"]
