name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Lint + format code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["39", "310", "311", "312", "313", "314"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files
