name: Publish on PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel twine build

      - name: Bundle
        run: python -m build

      - name: Publish package 🐍
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true
